name: ci

env:
  CONFIG_REPO_NAME: argo-pr-generator

on:
  push:
    branches:
      - "main"

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "building and testing the app ..."
  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        run: |
          docker build -t app:latest -f WebApplication1/Dockerfile .
          docker tag app:latest ${{ steps.login-ecr.outputs.registry }}/demo_scripts:${{ github.sha }}
          docker push ${{ steps.login-ecr.outputs.registry }}/demo_scripts:${{ github.sha }}

  promote-to-dev-environment:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - run: |
          echo "promoting into dev environment!"
          git config --global user.email ci-bot@argocd.com && git config --global user.name ci-bot
          echo "cloning config repo $CONFIG_REPO_NAME"
          git clone https://oauth2:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository_owner }}/$CONFIG_REPO_NAME.git
          cd $CONFIG_REPO_NAME
          echo "checkout main branch"
          git checkout main
          echo "updating image tag in values file"
          sed -i "s,tag:.*,tag:\ ${{ github.sha }}," helm/webapp/values.yaml
          git add . && git commit -m "update image tag"
          git push
